import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PreferencesSwitcher } from "@/features/ui/preferences-switcher";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      style={{ colorScheme: "light" }}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b border-zinc-200 px-6 py-3">
          <div className="mx-auto flex w-full max-w-5xl justify-end">
            <PreferencesSwitcher />
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
